# Generated by Django 3.0.5 on 2020-06-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('jurusan', models.CharField(max_length=30)),
                ('JK', models.CharField(max_length=30)),
                ('asal', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=30)),
                ('info', models.CharField(max_length=30)),
                ('dorongan', models.CharField(max_length=30)),
                ('alasan', models.CharField(max_length=30)),
                ('pendapat', models.CharField(max_length=30)),
                ('peluang', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='upload_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
