# Generated by Django 3.0.5 on 2020-06-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_dcluster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('sekolah', models.CharField(max_length=100)),
                ('lintang', models.CharField(max_length=30)),
                ('bujur', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='mahasiswa',
        ),
    ]
