# Generated by Django 3.0.5 on 2020-06-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_dcluster', '0002_auto_20200618_0903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='data_siswa',
        ),
    ]
