# Generated by Django 3.0.5 on 2020-06-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_dcluster', '0003_auto_20200618_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_siswa',
            name='bujur',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='data_siswa',
            name='lintang',
            field=models.FloatField(max_length=30),
        ),
    ]
