# Generated by Django 3.0.7 on 2020-08-30 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_dcluster', '0004_auto_20200618_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_data',
            name='isi',
            field=models.FileField(upload_to='documents\\'),
        ),
        migrations.CreateModel(
            name='cluster_siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField()),
                ('eucidian', models.FloatField(max_length=30)),
                ('cluster', models.IntegerField()),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_dcluster.data_siswa')),
            ],
        ),
    ]
