# Generated by Django 3.0.7 on 2020-08-31 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_dcluster', '0006_data_sekolah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster_siswa',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='cluster_siswa',
            name='eucidian',
        ),
    ]
