# Generated by Django 3.0.7 on 2020-09-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_dcluster', '0007_auto_20200831_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_sekolah',
            name='alamat',
        ),
    ]
